font_family JetBrainsMono Nerd Font
font_size 10.0
bold_font auto
italic_font auto
bold_italic_font auto

background_opacity 1
dynamic_background_opacity 1
confirm_os_window_close 0

# Animated cursor
cursor_trail 0

# change to x11 or wayland or leave auto
linux_display_server wayland

scrollback_lines 2000
wheel_scroll_min_lines 1

enable_audio_bell no

window_padding_width 4


# Theme #
background #111111
foreground #a0a0a0
cursor #bbbbbb
selection_background #9a9a9a
color0 #1b1d1e
color8 #505354
color1 #f92672
color9 #ff669d
color2 #a6e22e
color10 #beed5f
color3 #fd971f
color11 #e6db74
color4 #66d9ef
color12 #66d9ef
color5 #9e6ffe
color13 #9e6ffe
color6 #5e7175
color14 #a3babf
color7 #ccccc6
color15 #f8f8f2
selection_foreground #121212
