# Hide the cursor while typing
#
# Default is `false`
#
# hide-cursor-when-typing = false

# Ignore theme selection foreground color
#
# Default is false
#
# Example:
# ignore-selection-foreground-color = false

# Theme
theme = "Framer"
confirm-before-quit = false

# Font 

[fonts]
size = 13
use-drawable-chars = true

[fonts.regular]
family = "CaskaydiaCove Nerd Font"
style = "Normal"
width = "Normal"
weight = 400

[fonts.bold]
family = "CaskaydiaCove Nerd Font"
style = "Normal"
width = "Normal"
weight = 700

[fonts.italic]
family = "CaskaydiaCove Nerd Font"
style = "Italic"
width = "Normal"
weight = 400

[fonts.bold-italic]
family = "CaskaydiaCove Nerd Font"
style = "Italic"
width = "Normal"
weight = 700

# Renderer
[renderer]
performance = "high"
backend = "Vulkan"
level = 1
target-fps = 144
# disable-unfocused-render = false
# filters = ["NewPixieCrt",]

# General
[editor]
program = "micro"

[cursor]
shape = 'block'
blinking = false
blinking-interval = 800

[scroll]
multiplier = 4.0
divider = 1.0

[shell]
program = "/bin/zsh"
args = ["--login"]

# Environment variables
#
# Example:
# env-vars = []

# Example:
# use-fork = true

# args = []

# Bindings
#
# Create custom Key bindings for Rio terminal
# More information in: https://raphamorim.io/rio/docs/key-bindings
#
# Example:
# 
# keys = [
#   { key = "q", with = "super", action = "Quit" },
#   # Bytes[27, 91, 53, 126] is equivalent to "\x1b[5~"
#   { key = "home", with = "super | shift", bytes = [27, 91, 53, 126] }
# ]

[bindings]
keys = [
  # Enable VI mode on escape, when not in VI mode.
  { key = "home", with = "control", action= "ToggleFullScreen" },
]
