[keyboard]

bindings = [

#Text Keybinds
{ key = "PageUp", mods = "Control|Shift", action = "ScrollHalfPageUp" },
{ key = "PageDown", mods = "Control|Shift", action = "ScrollHalfPageDown" },
{ key = "ArrowUp", mods = "Control|Shift", action = "ScrollLineUp" },
{ key = "ArrowDown", mods = "Control|Shift", action = "ScrollLineDown" },

#Window Keybinds
{ key = "T", mods = "Control|Shift", action = "SpawnNewInstance" },
{ key = "Q", mods = "Alt", action = "Quit" },
{ key = "ArrowDown", mods = "Alt", action = "Minimize" },
{ key = "F12", action = "ToggleFullscreen" },

#Char Keybinds
{ key = "P", mods = "Control|Shift", chars = "micro /home/zaddy/.config/alacritty/keybinds.toml" },

]

[mouse]
bindings = [
{ mouse = "Forward", action = "PasteSelection"},
{ mouse = "Back", action = "CopySelection"}
]
